# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql2
  encoding: utf8
  database: Demoapp_development
  pool: 5
  username: root
  password: root

production:
  host: 127.8.58.130
  adapter: mysql
  database: railsdemoapp
  user: adminHug7hCM
  password: iGQzUl51pkK1
  socket: /var/lib/openshift/52fbca00500446165f0006f5/mysql//socket/mysql.sock
  port: 3306